services:
  library-management:
    container_name: library-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=${ASPNETCORE_FORWARDEDHEADERS_ENABLED}
      - JWT__SecretKey=${JWT__SecretKey}

      - CLOUDINARYSETTINGS__CLOUDNAME=${CLOUDINARYSETTINGS__CLOUDNAME}
      - CLOUDINARYSETTINGS__APIKEY=${CLOUDINARYSETTINGS__APIKEY}
      - CLOUDINARYSETTINGS__APISECRET=${CLOUDINARYSETTINGS__APISECRET}

      - CONNECTIONSTRINGS__MongoDbConnection=${CONNECTIONSTRINGS__MongoDbConnection}
      - CONNECTIONSTRINGS__PostgreSQLConnection=${CONNECTIONSTRINGS__PostgreSQLConnection}
      - GOOGLE__CLIENT__ID=${GOOGLE__CLIENT__ID}
      - GOOGLE__CLIENT__SECRET=${GOOGLE__CLIENT__SECRET}
      - SENDER_APIKEY=${SENDER_APIKEY}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - SENDER_NAME=${SENDER_NAME}
